[workspace]
members = [
    "crates/openasio-sys",
    "crates/openasio",
    "crates/openasio-driver-cpal",
    "crates/openasio-driver-alsa17h"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
